"""Generate a synthetic recruiting dataset for parser and ranking tests.

Writes CVs (PDF plus ground-truth JSON), job descriptions (JSON) and a blank
human-rating sheet (CSV). Names come from Faker; everything else comes from the
templates in this file. Nothing describes a real person.

The same seed, arguments and package versions (see requirements.txt) always
produce the same files.

    python generate.py --seed 42 --cvs 100 --jobs 20 --out output
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import random
import re
import unicodedata
from collections.abc import Callable
from dataclasses import dataclass
from importlib import metadata
from pathlib import Path
from typing import Any
from xml.sax.saxutils import escape

from faker import Faker
from reportlab.lib import colors
from reportlab.lib.enums import TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    BaseDocTemplate,
    Flowable,
    Frame,
    FrameBreak,
    NextPageTemplate,
    PageTemplate,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# Bump when templates or logic change: ratings collected for one version
# do not carry over to a dataset generated by another.
GENERATOR_VERSION = "1.0.0"

Record = dict[str, Any]
Styles = dict[str, ParagraphStyle]

SENIORITIES = ("junior", "mid", "senior", "lead")

# Fixed cycles instead of random draws, so every run covers each seniority and
# layout. Their lengths share no factor with the number of role families (10),
# which makes the family / seniority / layout combinations rotate.
CV_SENIORITY_CYCLE = ("mid", "junior", "senior", "mid", "lead", "junior", "senior", "mid", "senior")
JOB_SENIORITY_CYCLE = ("senior", "mid", "junior", "lead", "junior", "senior", "mid")
LAYOUT_CYCLE = ("classic", "two_column", "table", "classic", "plain", "two_column", "classic")

YEARS_RANGE = {"junior": (0.5, 2.5), "mid": (3.0, 5.5), "senior": (6.0, 10.0), "lead": (10.0, 16.0)}
JOB_COUNT = {"junior": (1, 2), "mid": (2, 3), "senior": (3, 4), "lead": (3, 5)}
CORE_SKILL_COUNT = {"junior": (4, 5), "mid": (5, 7), "senior": (7, 9), "lead": (8, 10)}
MIN_EXPERIENCE = {"junior": 0, "mid": 2, "senior": 5, "lead": 8}

# Locales whose names fit the built-in PDF fonts (Windows-1252 characters only).
LOCALES = ("en_US", "en_GB", "de_DE", "fr_FR", "es_ES", "it_IT", "nl_NL")

# Reserved for documentation and fiction, so they can never reach a real person.
EMAIL_DOMAINS = ("example.com", "example.org", "example.net")
AREA_CODES = ("202", "312", "415", "512", "617", "646")  # used with the fictional 555-01xx range

CITIES = (
    "Berlin, Germany",
    "Munich, Germany",
    "Paris, France",
    "Lyon, France",
    "Madrid, Spain",
    "Barcelona, Spain",
    "Milan, Italy",
    "Amsterdam, Netherlands",
    "Dublin, Ireland",
    "London, UK",
    "Manchester, UK",
    "Bucharest, Romania",
    "Cluj-Napoca, Romania",
    "Vienna, Austria",
    "Lisbon, Portugal",
    "Warsaw, Poland",
    "Austin, TX",
    "Boston, MA",
    "Chicago, IL",
    "Seattle, WA",
)

JOB_LOCATIONS = (
    "Remote (EU)",
    "Remote (US/EU)",
    "Berlin, Germany (hybrid)",
    "Bucharest, Romania",
    "London, UK (hybrid)",
    "Amsterdam, Netherlands",
    "Dublin, Ireland",
    "Austin, TX (on-site)",
    "Paris, France",
    "Madrid, Spain (hybrid)",
)

# Invented organisations. Any match with a real one is a coincidence.
COMPANIES = (
    "Nimbuscraft Labs",
    "Bluepeak Systems",
    "Quartzline Software",
    "Ferrowind Technologies",
    "Lumenfold Digital",
    "Oakhaven Analytics",
    "Tidewater Robotics",
    "Brightloom Studio",
    "Corvid Logic",
    "Halcyon Freight",
    "Meridian Nine",
    "Stonebridge Health",
    "Vantaro Group",
    "Kestrelworks",
    "Pinecrest Mobility",
    "Aurelia Payments",
    "Driftwood Media",
    "Solstice Energy Labs",
    "Marlowe Retail",
    "Copperfield Insurance",
    "Zephyr Travel Tech",
    "Ironbark Logistics",
    "Skylark Education",
    "Wavecrest Telecom",
    "Hollowell Foods",
    "Northgate Devices",
    "Emberline Games",
    "Saffron Street Bank",
    "Glasswing Bio",
    "Tallgrass Cloud",
)

INSTITUTIONS = (
    "Northfield Technical University",
    "Lakeshore University",
    "Eastbridge Institute of Technology",
    "Riverton College",
    "Westmark University of Applied Sciences",
    "Harcastle University",
    "Solvang Polytechnic",
    "Ardenne Business School",
    "Kestrel State University",
    "Dunmore Institute of Design",
    "Valmont University",
    "Greyfield College",
    "Saint Albrecht University",
    "Polytechnic University of Maribel",
)

SOFT_SKILLS = (
    "Communication",
    "Mentoring",
    "Agile",
    "Scrum",
    "Problem Solving",
    "Technical Writing",
    "Presentation Skills",
    "Stakeholder Communication",
)

LANGUAGES = (
    "German",
    "French",
    "Spanish",
    "Italian",
    "Dutch",
    "Romanian",
    "Portuguese",
    "Polish",
)
LANGUAGE_LEVELS = ("fluent", "professional", "intermediate", "basic", "B2", "C1")
NATIONALITIES = (
    "German",
    "French",
    "Spanish",
    "Italian",
    "Dutch",
    "Irish",
    "British",
    "American",
    "Romanian",
    "Austrian",
)

HEADINGS = {
    "summary": ("Summary", "Profile", "About Me", "Professional Summary"),
    "experience": (
        "Experience",
        "Work Experience",
        "Professional Experience",
        "Employment History",
        "Career History",
    ),
    "skills": ("Skills", "Technical Skills", "Core Competencies", "Key Skills"),
    "education": ("Education", "Education & Training", "Academic Background"),
    "languages": ("Languages", "Language Skills"),
    "certifications": ("Certifications", "Courses & Certificates"),
}

SUMMARY_CLOSERS = (
    "Comfortable working in cross-functional agile teams.",
    "Looking for a role with ownership and room to grow.",
    "Enjoys mentoring and clear documentation.",
    "Known for reliable delivery and pragmatic solutions.",
)

FONTS = {"Helvetica": "Helvetica-Bold", "Times-Roman": "Times-Bold", "Courier": "Courier-Bold"}
MONTH_ABBR = ("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")
MONTH_NAMES = (
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
)


@dataclass(frozen=True)
class Family:
    """One job family: its titles, skills and the sentences used to describe the work."""

    key: str
    department: str
    titles: tuple[str, str, str, str]  # junior, mid, senior, lead
    core: tuple[str, ...]
    extra: tuple[str, ...]
    bullets: tuple[str, ...]  # CV achievements; {n} is a percentage or amount, {m} a small count
    duties: tuple[str, ...]  # job-description responsibilities
    fields: tuple[str, ...]
    bachelor: str
    master: str
    certs: tuple[str, ...]


_ENGINEERING_FIELDS = (
    "Computer Science",
    "Software Engineering",
    "Information Systems",
    "Computer Engineering",
)

FAMILIES = (
    Family(
        key="backend",
        department="Engineering",
        titles=(
            "Junior Backend Developer",
            "Backend Developer",
            "Senior Backend Engineer",
            "Lead Backend Engineer",
        ),
        core=(
            "Python",
            "Java",
            "Go",
            "FastAPI",
            "Django",
            "Spring Boot",
            "PostgreSQL",
            "REST APIs",
            "Docker",
            "Redis",
            "SQL",
            "Microservices",
        ),
        extra=(
            "Kafka",
            "RabbitMQ",
            "gRPC",
            "GraphQL",
            "MongoDB",
            "Celery",
            "AWS",
            "Kubernetes",
            "pytest",
            "CI/CD",
        ),
        bullets=(
            "Built and maintained backend services used by {m} internal teams",
            "Designed REST endpoints and data models for new product features",
            "Cut average response time by {n}% by profiling queries and adding caching",
            "Wrote unit and integration tests, raising coverage by {n} percentage points",
            "Migrated a legacy module to a new stack together with QA and product",
            "Reviewed pull requests and supported {m} newer developers",
        ),
        duties=(
            "Design, build and operate the services and APIs behind our product",
            "Model data and write efficient queries",
            "Write automated tests and take part in code reviews",
            "Work with product, frontend and QA to ship features end to end",
            "Monitor production and fix issues quickly",
        ),
        fields=_ENGINEERING_FIELDS,
        bachelor="B.Sc.",
        master="M.Sc.",
        certs=(
            "AWS Certified Developer - Associate",
            "Oracle Certified Professional: Java SE Programmer",
        ),
    ),
    Family(
        key="frontend",
        department="Engineering",
        titles=(
            "Junior Frontend Developer",
            "Frontend Developer",
            "Senior Frontend Engineer",
            "Frontend Tech Lead",
        ),
        core=(
            "JavaScript",
            "TypeScript",
            "React",
            "Next.js",
            "HTML",
            "CSS",
            "Tailwind CSS",
            "Redux",
            "Vue.js",
            "Web Accessibility",
            "Jest",
            "Responsive Design",
        ),
        extra=(
            "Webpack",
            "Vite",
            "Storybook",
            "Cypress",
            "GraphQL",
            "Figma",
            "Node.js",
            "Playwright",
            "Sass",
        ),
        bullets=(
            "Built reusable UI components for the main web application",
            "Improved page load time by {n}% through code splitting and image optimisation",
            "Worked with designers to turn mock-ups into accessible, responsive pages",
            "Added automated tests that caught regressions before release",
            "Maintained a shared component library used across {m} products",
            "Led the move of {m} legacy screens to a modern framework",
        ),
        duties=(
            "Build accessible, responsive user interfaces",
            "Turn designs into reusable components",
            "Write automated tests for critical user journeys",
            "Measure and improve front-end performance",
            "Work closely with designers and backend developers",
        ),
        fields=_ENGINEERING_FIELDS,
        bachelor="B.Sc.",
        master="M.Sc.",
        certs=("Front-End Web Development Certificate", "Web Accessibility Fundamentals"),
    ),
    Family(
        key="data_science",
        department="Data",
        titles=(
            "Junior Data Scientist",
            "Data Scientist",
            "Senior Data Scientist",
            "Lead Data Scientist",
        ),
        core=(
            "Python",
            "Machine Learning",
            "pandas",
            "scikit-learn",
            "PyTorch",
            "TensorFlow",
            "SQL",
            "Statistics",
            "NLP",
            "Feature Engineering",
            "Data Visualization",
            "Jupyter",
        ),
        extra=(
            "Spark",
            "MLflow",
            "Airflow",
            "Docker",
            "Deep Learning",
            "XGBoost",
            "Computer Vision",
            "A/B Testing",
            "Hugging Face Transformers",
        ),
        bullets=(
            "Trained and evaluated models for a ranking problem",
            "Improved model precision by {n}% through feature work and error analysis",
            "Built data pipelines and notebooks used by {m} analysts",
            "Presented findings to non-technical stakeholders and turned them into roadmap items",
            "Set up experiment tracking and reproducible training runs",
            "Designed and analysed {m} online experiments",
        ),
        duties=(
            "Develop, evaluate and improve machine-learning models",
            "Explore data and communicate findings clearly",
            "Build reproducible training and evaluation pipelines",
            "Work with engineers to put models into production",
            "Monitor model quality and investigate errors",
        ),
        fields=("Data Science", "Statistics", "Applied Mathematics", "Computer Science"),
        bachelor="B.Sc.",
        master="M.Sc.",
        certs=("Machine Learning Specialization", "TensorFlow Developer Certificate"),
    ),
    Family(
        key="devops",
        department="Platform",
        titles=(
            "Junior DevOps Engineer",
            "DevOps Engineer",
            "Senior DevOps Engineer",
            "Lead Platform Engineer",
        ),
        core=(
            "Linux",
            "Docker",
            "Kubernetes",
            "Terraform",
            "AWS",
            "CI/CD",
            "Ansible",
            "Bash",
            "Monitoring",
            "GitHub Actions",
            "Networking",
            "Prometheus",
        ),
        extra=(
            "Azure",
            "GCP",
            "Helm",
            "Grafana",
            "Python",
            "Jenkins",
            "ArgoCD",
            "Nginx",
            "Vault",
        ),
        bullets=(
            "Automated deployments, reducing release time by {n}%",
            "Ran and monitored production clusters serving {m} services",
            "Wrote infrastructure as code and reviewed changes from other teams",
            "Introduced alerting and dashboards that shortened incident response by {n}%",
            "Hardened build pipelines and moved secrets into a managed store",
            "Cut the monthly cloud bill by {n}% by right-sizing workloads",
        ),
        duties=(
            "Run and improve our cloud infrastructure",
            "Automate builds, tests and deployments",
            "Manage infrastructure as code",
            "Set up monitoring, alerting and incident response",
            "Help development teams ship safely and often",
        ),
        fields=_ENGINEERING_FIELDS,
        bachelor="B.Sc.",
        master="M.Sc.",
        certs=(
            "Certified Kubernetes Administrator (CKA)",
            "AWS Certified Solutions Architect - Associate",
        ),
    ),
    Family(
        key="qa",
        department="Quality Assurance",
        titles=(
            "Junior QA Tester",
            "QA Engineer",
            "Senior QA Automation Engineer",
            "QA Lead",
        ),
        core=(
            "Test Automation",
            "Selenium",
            "Playwright",
            "API Testing",
            "Test Planning",
            "Postman",
            "Python",
            "Java",
            "JIRA",
            "Regression Testing",
            "Cypress",
            "Performance Testing",
        ),
        extra=(
            "JMeter",
            "Cucumber",
            "CI/CD",
            "SQL",
            "TestRail",
            "Appium",
            "k6",
            "Agile",
        ),
        bullets=(
            "Wrote automated test suites for web and API layers",
            "Reduced manual regression effort by {n}% through automation",
            "Designed test plans and test cases for {m} product areas",
            "Reported, reproduced and tracked defects together with developers",
            "Added API and performance checks to the release pipeline",
            "Coached {m} testers on writing maintainable automated tests",
        ),
        duties=(
            "Plan and run tests for new features",
            "Build and maintain automated test suites",
            "Report and track defects with developers",
            "Add quality checks to the release pipeline",
            "Take part in refinement to make stories testable",
        ),
        fields=_ENGINEERING_FIELDS,
        bachelor="B.Sc.",
        master="M.Sc.",
        certs=("ISTQB Certified Tester Foundation Level", "Certified Agile Tester"),
    ),
    Family(
        key="mobile",
        department="Engineering",
        titles=(
            "Junior Mobile Developer",
            "Mobile Developer",
            "Senior Mobile Engineer",
            "Mobile Engineering Lead",
        ),
        core=(
            "Kotlin",
            "Swift",
            "Android",
            "iOS",
            "React Native",
            "Flutter",
            "REST APIs",
            "Jetpack Compose",
            "SwiftUI",
            "Mobile UI Design",
            "Firebase",
            "Git",
        ),
        extra=(
            "Dart",
            "Objective-C",
            "GraphQL",
            "CI/CD",
            "Push Notifications",
            "SQLite",
            "Fastlane",
            "Unit Testing",
        ),
        bullets=(
            "Shipped new app features from design to store release",
            "Reduced crash rate by {n}% through better error handling and monitoring",
            "Integrated REST back ends, offline storage and push notifications",
            "Published {m} releases to the app stores and handled review feedback",
            "Refactored legacy screens, improving start-up time by {n}%",
            "Set up automated builds and tests for {m} apps",
        ),
        duties=(
            "Build and ship features for our mobile apps",
            "Integrate APIs, offline storage and notifications",
            "Keep the apps fast, stable and accessible",
            "Publish releases to the app stores",
            "Work with designers and backend developers",
        ),
        fields=_ENGINEERING_FIELDS,
        bachelor="B.Sc.",
        master="M.Sc.",
        certs=("Associate Android Developer", "iOS App Development Certificate"),
    ),
    Family(
        key="data_analyst",
        department="Data",
        titles=(
            "Junior Data Analyst",
            "Data Analyst",
            "Senior Data Analyst",
            "Analytics Lead",
        ),
        core=(
            "SQL",
            "Excel",
            "Power BI",
            "Tableau",
            "Python",
            "Data Visualization",
            "Statistics",
            "Reporting",
            "Data Cleaning",
            "Dashboards",
            "pandas",
            "Stakeholder Communication",
        ),
        extra=(
            "Looker",
            "dbt",
            "Google Analytics",
            "R",
            "A/B Testing",
            "BigQuery",
            "Snowflake",
            "Forecasting",
        ),
        bullets=(
            "Built dashboards and recurring reports for sales and operations",
            "Cleaned and combined data from {m} sources for monthly reporting",
            "Automated a manual report, saving about {n} hours per month",
            "Analysed campaign and product data and presented recommendations",
            "Defined metrics with stakeholders and documented how they are calculated",
            "Trained {m} colleagues to build their own reports",
        ),
        duties=(
            "Build dashboards and reports for business teams",
            "Clean, combine and validate data from several sources",
            "Answer business questions with clear analysis",
            "Define and document metrics with stakeholders",
            "Automate recurring reporting",
        ),
        fields=("Economics", "Statistics", "Business Informatics", "Mathematics"),
        bachelor="B.Sc.",
        master="M.Sc.",
        certs=("Google Data Analytics Certificate", "Microsoft Power BI Data Analyst Associate"),
    ),
    Family(
        key="product",
        department="Product",
        titles=(
            "Associate Product Manager",
            "Product Manager",
            "Senior Product Manager",
            "Head of Product",
        ),
        core=(
            "Product Strategy",
            "Roadmapping",
            "User Research",
            "Agile",
            "Stakeholder Management",
            "Backlog Prioritization",
            "Data Analysis",
            "A/B Testing",
            "User Stories",
            "Go-to-Market",
            "Scrum",
            "KPI Definition",
        ),
        extra=(
            "SQL",
            "JIRA",
            "Figma",
            "OKRs",
            "Market Research",
            "Pricing",
            "Product Analytics",
            "Customer Interviews",
        ),
        bullets=(
            "Owned the roadmap and backlog for a product used by {m} customer teams",
            "Ran user interviews and turned the findings into prioritised user stories",
            "Launched a feature that raised activation by {n}%",
            "Worked daily with engineering and design in an agile team",
            "Defined success metrics and reviewed them with stakeholders every month",
            "Coordinated {m} releases across engineering, sales and support",
        ),
        duties=(
            "Own the roadmap and backlog for a product area",
            "Talk to users and turn what you learn into priorities",
            "Write clear user stories and acceptance criteria",
            "Define success metrics and track outcomes",
            "Work daily with engineering, design and stakeholders",
        ),
        fields=("Business Administration", "Economics", "Information Systems"),
        bachelor="B.A.",
        master="M.Sc.",
        certs=("Certified Scrum Product Owner (CSPO)", "Product Management Certificate"),
    ),
    Family(
        key="ux_design",
        department="Design",
        titles=(
            "Junior UX Designer",
            "UX Designer",
            "Senior UX Designer",
            "Lead Product Designer",
        ),
        core=(
            "User Research",
            "Wireframing",
            "Prototyping",
            "Figma",
            "Usability Testing",
            "Interaction Design",
            "Design Systems",
            "Information Architecture",
            "Visual Design",
            "Accessibility",
            "User Flows",
            "Sketch",
        ),
        extra=(
            "Adobe XD",
            "HTML",
            "CSS",
            "Design Thinking",
            "Journey Mapping",
            "Illustration",
            "Motion Design",
            "Workshop Facilitation",
        ),
        bullets=(
            "Designed user flows, wireframes and interactive prototypes",
            "Ran usability tests with {m} participants and iterated on the results",
            "Contributed components and guidelines to the design system",
            "Redesigned a key journey, lifting task completion by {n}%",
            "Worked with developers to ship accessible interfaces",
            "Facilitated {m} discovery workshops with stakeholders",
        ),
        duties=(
            "Design user flows, wireframes and prototypes",
            "Plan and run user research and usability tests",
            "Maintain and extend the design system",
            "Work with developers to ship accessible interfaces",
            "Present design decisions to stakeholders",
        ),
        fields=("Interaction Design", "Graphic Design", "Psychology", "Media Design"),
        bachelor="B.A.",
        master="M.A.",
        certs=("Google UX Design Certificate", "Certified Usability Analyst"),
    ),
    Family(
        key="marketing",
        department="Marketing",
        titles=(
            "Marketing Assistant",
            "Marketing Specialist",
            "Senior Marketing Manager",
            "Head of Marketing",
        ),
        core=(
            "Digital Marketing",
            "SEO",
            "Content Marketing",
            "Google Analytics",
            "Social Media",
            "Email Marketing",
            "Copywriting",
            "Campaign Management",
            "Paid Search",
            "Marketing Automation",
            "Brand Strategy",
            "Market Research",
        ),
        extra=(
            "HubSpot",
            "Google Ads",
            "CRM",
            "A/B Testing",
            "Event Marketing",
            "Public Relations",
            "Video Production",
            "Canva",
        ),
        bullets=(
            "Planned and ran campaigns across search, social and email",
            "Grew organic traffic by {n}% through content and technical improvements",
            "Managed a monthly budget and reported results to leadership",
            "Wrote and edited copy for web pages, newsletters and social posts",
            "Coordinated {m} product launches with sales and product teams",
            "Raised newsletter click-through by {n}% with segmented content",
        ),
        duties=(
            "Plan and run multi-channel campaigns",
            "Create and edit content for web, email and social media",
            "Track results and report on performance",
            "Manage budgets and agencies",
            "Work with sales and product on launches",
        ),
        fields=("Marketing", "Communication", "Business Administration"),
        bachelor="B.A.",
        master="M.A.",
        certs=("Google Ads Search Certification", "HubSpot Content Marketing Certification"),
    ),
)


# --------------------------------------------------------------------------- CV content


def _slug(text: str) -> str:
    """Lower-case ASCII version of a name part, for building an email address."""
    folded = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")
    return re.sub(r"[^a-z0-9]+", ".", folded.lower()).strip(".")


def _year_month(index: int) -> str:
    """Convert a month counter (year * 12 + zero-based month) to 'YYYY-MM'."""
    year, month = divmod(index, 12)
    return f"{year}-{month + 1:02d}"


def _work_history(
    rng: random.Random, family: Family, level: int, ref_year: int, skill_pool: list[str]
) -> tuple[list[Record], int]:
    """Build the jobs, newest first, and return them with the total months worked."""
    seniority = SENIORITIES[level]
    low, high = YEARS_RANGE[seniority]
    total_months = int(rng.uniform(low, high) * 12)
    count = min(rng.randint(*JOB_COUNT[seniority]), max(1, total_months // 8))
    weights = [rng.uniform(0.6, 1.6) for _ in range(count)]
    scale = total_months / sum(weights)
    months = [max(6, round(weight * scale)) for weight in weights]

    today = ref_year * 12 + 8  # September of the reference year
    jobs: list[Record] = []
    job_level = level
    newer_start: int | None = None
    for i, company in enumerate(rng.sample(COMPANIES, count)):
        if newer_start is None:
            is_current = rng.random() < 0.8
            end = today if is_current else today - rng.randint(1, 6)
        else:
            is_current = False
            end = newer_start - rng.randint(0, 3)
            if rng.random() < 0.75:
                job_level = max(0, job_level - 1)
        start = end - months[i]

        bullets = []
        for template in rng.sample(family.bullets, rng.randint(2, 4)):
            text = template.format(n=rng.randrange(10, 50, 5), m=rng.randint(2, 8))
            if rng.random() < 0.6:
                text += f" ({', '.join(rng.sample(skill_pool, 2))})"
            bullets.append(text)

        jobs.append(
            {
                "title": family.titles[job_level],
                "company": company,
                "years": round(months[i] / 12, 1),
                "summary": bullets[0],
                "start": _year_month(start),
                "end": None if is_current else _year_month(end),
                "bullets": bullets,
            }
        )
        newer_start = start
    return jobs, sum(months)


def _education(
    rng: random.Random, family: Family, level: int, first_job_year: int
) -> list[Record]:
    grad_year = first_job_year - rng.randint(0, 1)
    schools = rng.sample(INSTITUTIONS, 2)
    field = rng.choice(family.fields)
    if level >= 1 and rng.random() < 0.4:
        return [
            {
                "degree": f"{family.master} {field}",
                "institution": schools[0],
                "grad_year": grad_year,
            },
            {
                "degree": f"{family.bachelor} {rng.choice(family.fields)}",
                "institution": schools[1],
                "grad_year": grad_year - 2,
            },
        ]
    return [
        {"degree": f"{family.bachelor} {field}", "institution": schools[0], "grad_year": grad_year}
    ]


def _summary(rng: random.Random, headline: str, years: float, skills: list[str]) -> str:
    if years < 1:
        span = "under a year"
    else:
        span = f"{int(years)} year{'' if int(years) == 1 else 's'}"
    first, second, third = skills[:3]
    closer = rng.choice(SUMMARY_CLOSERS)
    return rng.choice(
        (
            f"{headline} with {span} of experience in {first}, {second} and {third}. {closer}",
            f"{span.capitalize()} of hands-on work with {first} and {second}, "
            f"most recently as {headline}. {closer}",
            f"My most recent role is {headline}; most of my work involves {first}, {second} "
            f"and {third}. {closer}",
        )
    )


def build_cv(
    index: int, seed: int, ref_year: int, fakers: dict[str, Faker]
) -> tuple[Record, Record]:
    """Return the ground truth for one CV and the options used to draw its PDF.

    Each CV has its own random stream, so CV number N is the same whatever --cvs is.
    """
    rng = random.Random(f"{seed}:cv:{index}")
    family = FAMILIES[index % len(FAMILIES)]
    seniority = CV_SENIORITY_CYCLE[index % len(CV_SENIORITY_CYCLE)]
    layout = LAYOUT_CYCLE[index % len(LAYOUT_CYCLE)]
    level = SENIORITIES.index(seniority)
    candidate_id = f"C{index + 1:03d}"

    fake = fakers[rng.choice(LOCALES)]
    fake.seed_instance(rng.getrandbits(32))
    first_name, last_name = fake.first_name(), fake.last_name()
    local_part = ".".join(part for part in (_slug(first_name), _slug(last_name)) if part)
    local_part = local_part or "candidate"
    if rng.random() < 0.4:
        local_part += str(rng.randint(1, 99))
    email = f"{local_part}@{rng.choice(EMAIL_DOMAINS)}"
    phone = f"+1-{rng.choice(AREA_CODES)}-555-01{rng.randint(0, 99):02d}"
    location = rng.choice(CITIES)

    low, high = CORE_SKILL_COUNT[seniority]
    core = rng.sample(family.core, rng.randint(low, high))
    extra = rng.sample(family.extra, rng.randint(1, 3))
    other_family = rng.choice([f for f in FAMILIES if f.key != family.key])
    unrelated = rng.sample(other_family.core, rng.randint(0, 2))
    soft = rng.sample(SOFT_SKILLS, rng.randint(0, 2))
    skills = list(dict.fromkeys(core + extra + unrelated + soft))
    rng.shuffle(skills)

    history, total_months = _work_history(rng, family, level, ref_year, core + extra)
    experience_years = round(total_months / 12, 1)
    education = _education(rng, family, level, int(history[-1]["start"][:4]))
    headline = history[0]["title"]

    languages = [f"English ({rng.choice(('native', 'fluent', 'C1'))})"]
    for language in rng.sample(LANGUAGES, rng.randint(0, 2)):
        languages.append(f"{language} ({rng.choice(LANGUAGE_LEVELS)})")
    certifications = rng.sample(family.certs, rng.randint(0, len(family.certs)))

    # Some real CVs carry details a scorer must never use. A few synthetic ones do
    # too, so tests can check that the parser and scorer leave them out.
    sensitive_noise = None
    if rng.random() < 0.15:
        birth_year = education[-1]["grad_year"] - rng.randint(21, 24)
        sensitive_noise = {
            "date_of_birth": f"{rng.randint(1, 28)} {rng.choice(MONTH_NAMES)} {birth_year}",
            "nationality": rng.choice(NATIONALITIES),
        }

    cv = {
        "candidate_id": candidate_id,
        "synthetic": True,
        "full_name": f"{first_name} {last_name}",
        "email": email,
        "phone": phone,
        "location": location,
        "headline": headline,
        "role_family": family.key,
        "seniority": seniority,
        "layout": layout,
        "pdf_file": f"{candidate_id}.pdf",
        "summary": _summary(rng, headline, experience_years, core),
        "languages": languages,
        "certifications": certifications,
        # Same shape as candidates.parsed_data in the API, plus start, end and bullets per job.
        "parsed_data": {
            "skills": skills,
            "experience_years": experience_years,
            "education": education,
            "work_history": history,
        },
        "sensitive_noise": sensitive_noise,
    }
    options = {
        "font": "Courier" if layout == "plain" else rng.choice(("Helvetica", "Times-Roman")),
        "size": rng.choice((9.0, 9.5, 10.0)),
        "date_style": rng.choice(("year", "month_year", "numeric")),
        "bullet": rng.choice(("•", "-", "–")),
        "headings": {key: rng.choice(choices) for key, choices in HEADINGS.items()},
        "skills_style": rng.choice(("commas", "bullets", "pipes")),
        "skills_first": rng.random() < 0.3,
        "sidebar_left": rng.random() < 0.7,
    }
    return cv, options


# --------------------------------------------------------------------------- PDF layouts


def _doc_args(cv: Record) -> Record:
    """Settings shared by every layout.

    `invariant` fixes the timestamps and document ID, and switching compression off
    removes the dependency on the local zlib build, so the bytes are repeatable.
    """
    return {
        "pagesize": A4,
        "title": f"Synthetic CV {cv['candidate_id']}",
        "author": "ats-scorer synthetic data generator",
        "subject": "Synthetic test data. Not a real person.",
        "invariant": 1,
        "pageCompression": 0,
    }


def _styles(options: Record, shrink: float = 0.0) -> Styles:
    font = options["font"]
    bold = FONTS[font]
    size = options["size"] - shrink
    grey = colors.HexColor("#555555")
    return {
        "name": ParagraphStyle(
            "name", fontName=bold, fontSize=size + 9, leading=size + 13, spaceAfter=2
        ),
        "headline": ParagraphStyle(
            "headline",
            fontName=font,
            fontSize=size + 2,
            leading=size + 6,
            textColor=grey,
            spaceAfter=4,
        ),
        "heading": ParagraphStyle(
            "heading",
            fontName=bold,
            fontSize=size + 1.5,
            leading=size + 5,
            spaceBefore=9,
            spaceAfter=3,
        ),
        "body": ParagraphStyle("body", fontName=font, fontSize=size, leading=size + 3.5),
        "small": ParagraphStyle(
            "small", fontName=font, fontSize=size - 1, leading=size + 2, textColor=grey
        ),
        "right": ParagraphStyle(
            "right", fontName=font, fontSize=size - 1, leading=size + 2, alignment=TA_RIGHT
        ),
        "bullet": ParagraphStyle(
            "bullet",
            fontName=font,
            fontSize=size,
            leading=size + 3.5,
            leftIndent=10,
            bulletIndent=1,
            bulletFontName=font,
            bulletFontSize=size,
        ),
    }


def _p(text: str, style: ParagraphStyle) -> Paragraph:
    """Paragraph from plain text, escaped so '&' or '<' in the data cannot break the markup."""
    return Paragraph(escape(text), style)


def _bullets(items: list[str], options: Record, style: ParagraphStyle) -> list[Flowable]:
    return [Paragraph(escape(item), style, bulletText=options["bullet"]) for item in items]


def _contact(cv: Record) -> list[str]:
    return [cv["email"], cv["phone"], cv["location"]]


def _format_date(value: str | None, style: str) -> str:
    if value is None:
        return "Present"
    year, month = value.split("-")
    if style == "year":
        return year
    if style == "numeric":
        return f"{month}/{year}"
    return f"{MONTH_ABBR[int(month) - 1]} {year}"


def _date_range(job: Record, style: str) -> str:
    return f"{_format_date(job['start'], style)} - {_format_date(job['end'], style)}"


def _noise_block(cv: Record, st: Styles) -> list[Flowable]:
    noise = cv["sensitive_noise"]
    if not noise:
        return []
    line = f"Date of birth: {noise['date_of_birth']} | Nationality: {noise['nationality']}"
    return [_p(line, st["small"])]


def _experience_block(cv: Record, options: Record, st: Styles) -> list[Flowable]:
    out: list[Flowable] = []
    for job in cv["parsed_data"]["work_history"]:
        title_line = f"<b>{escape(job['title'])}</b>, {escape(job['company'])}"
        out.append(Paragraph(title_line, st["body"]))
        out.append(_p(_date_range(job, options["date_style"]), st["small"]))
        out += _bullets(job["bullets"], options, st["bullet"])
        out.append(Spacer(1, 5))
    return out


def _skills_block(cv: Record, options: Record, st: Styles) -> list[Flowable]:
    skills = cv["parsed_data"]["skills"]
    if options["skills_style"] == "bullets":
        return _bullets(skills, options, st["bullet"])
    separator = " | " if options["skills_style"] == "pipes" else ", "
    return [_p(separator.join(skills), st["body"])]


def _education_block(cv: Record, st: Styles) -> list[Flowable]:
    out: list[Flowable] = []
    for entry in cv["parsed_data"]["education"]:
        out.append(Paragraph(f"<b>{escape(entry['degree'])}</b>", st["body"]))
        out.append(_p(f"{entry['institution']}, {entry['grad_year']}", st["small"]))
    return out


def _extras_block(cv: Record, options: Record, st: Styles) -> list[Flowable]:
    headings = options["headings"]
    out = [_p(headings["languages"], st["heading"]), _p(", ".join(cv["languages"]), st["body"])]
    if cv["certifications"]:
        out.append(_p(headings["certifications"], st["heading"]))
        out += [_p(name, st["body"]) for name in cv["certifications"]]
    return out


def render_classic(cv: Record, options: Record, path: Path) -> None:
    """Single column with clear headings: the easy case for a parser."""
    st = _styles(options)
    headings = options["headings"]
    doc = SimpleDocTemplate(
        str(path),
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
        **_doc_args(cv),
    )
    skills = [_p(headings["skills"], st["heading"]), *_skills_block(cv, options, st)]
    experience = [_p(headings["experience"], st["heading"]), *_experience_block(cv, options, st)]
    story = [
        _p(cv["full_name"], st["name"]),
        _p(cv["headline"], st["headline"]),
        _p(" | ".join(_contact(cv)), st["small"]),
        *_noise_block(cv, st),
        _p(headings["summary"], st["heading"]),
        _p(cv["summary"], st["body"]),
    ]
    story += skills + experience if options["skills_first"] else experience + skills
    story += [_p(headings["education"], st["heading"]), *_education_block(cv, st)]
    story += _extras_block(cv, options, st)
    doc.build(story)


def render_two_column(cv: Record, options: Record, path: Path) -> None:
    """Shaded sidebar next to the main column.

    The sidebar is written to the PDF first even when it sits on the right, so the
    order of the text in the file does not always match left-to-right reading order.
    """
    st = _styles(options)
    side_st = _styles(options, shrink=1.0)
    headings = options["headings"]
    page_width, page_height = A4
    margin, gutter, side_width = 12 * mm, 6 * mm, 60 * mm
    main_width = page_width - 2 * margin - gutter - side_width
    frame_height = page_height - 2 * margin
    if options["sidebar_left"]:
        side_x, main_x = margin, margin + side_width + gutter
    else:
        main_x, side_x = margin, margin + main_width + gutter

    def shade_sidebar(canvas: Any, _doc: Any) -> None:
        canvas.saveState()
        canvas.setFillColor(colors.HexColor("#EEF1F5"))
        canvas.rect(side_x - 2 * mm, 0, side_width + 4 * mm, page_height, stroke=0, fill=1)
        canvas.restoreState()

    doc = BaseDocTemplate(str(path), **_doc_args(cv))
    doc.addPageTemplates(
        [
            PageTemplate(
                id="first",
                frames=[
                    Frame(side_x, margin, side_width, frame_height, id="side"),
                    Frame(main_x, margin, main_width, frame_height, id="main"),
                ],
                onPage=shade_sidebar,
            ),
            # Later pages continue the main column only.
            PageTemplate(id="rest", frames=[Frame(main_x, margin, main_width, frame_height)]),
        ]
    )
    sidebar = [
        _p("Contact", side_st["heading"]),
        *[_p(line, side_st["body"]) for line in _contact(cv)],
        *_noise_block(cv, side_st),
        _p(headings["skills"], side_st["heading"]),
        *_bullets(cv["parsed_data"]["skills"], options, side_st["bullet"]),
        _p(headings["education"], side_st["heading"]),
        *_education_block(cv, side_st),
        *_extras_block(cv, options, side_st),
    ]
    main = [
        _p(cv["full_name"], st["name"]),
        _p(cv["headline"], st["headline"]),
        _p(headings["summary"], st["heading"]),
        _p(cv["summary"], st["body"]),
        _p(headings["experience"], st["heading"]),
        *_experience_block(cv, options, st),
    ]
    doc.build([NextPageTemplate("rest"), *sidebar, FrameBreak(), *main])


def render_table(cv: Record, options: Record, path: Path) -> None:
    """Header, experience, skills and education as tables, with dates in their own column."""
    st = _styles(options)
    headings = options["headings"]
    margin = 16 * mm
    width = A4[0] - 2 * margin - 12  # the frame adds 6pt of padding on each side
    doc = SimpleDocTemplate(
        str(path),
        leftMargin=margin,
        rightMargin=margin,
        topMargin=margin,
        bottomMargin=margin,
        **_doc_args(cv),
    )
    flush = [
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
    ]

    contact = "<br/>".join(escape(line) for line in _contact(cv))
    header = Table(
        [
            [
                [_p(cv["full_name"], st["name"]), _p(cv["headline"], st["headline"])],
                Paragraph(contact, st["right"]),
            ]
        ],
        colWidths=[width * 0.62, width * 0.38],
    )
    header.setStyle(TableStyle([*flush, ("LINEBELOW", (0, 0), (-1, -1), 0.8, colors.black)]))

    date_width = 36 * mm
    rows = []
    for job in cv["parsed_data"]["work_history"]:
        details = [
            Paragraph(f"<b>{escape(job['title'])}</b>", st["body"]),
            _p(job["company"], st["small"]),
            *_bullets(job["bullets"], options, st["bullet"]),
        ]
        rows.append([_p(_date_range(job, options["date_style"]), st["small"]), details])
    experience = Table(rows, colWidths=[date_width, width - date_width])
    experience.setStyle(
        TableStyle(
            [
                *flush,
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.lightgrey),
            ]
        )
    )

    columns = 3
    skills = list(cv["parsed_data"]["skills"])
    skills += [""] * (-len(skills) % columns)
    grid = Table(
        [skills[i : i + columns] for i in range(0, len(skills), columns)],
        colWidths=[width / columns] * columns,
    )
    grid.setStyle(
        TableStyle(
            [
                ("FONT", (0, 0), (-1, -1), options["font"], options["size"] - 0.5),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
            ]
        )
    )

    education = Table(
        [
            [str(entry["grad_year"]), _p(f"{entry['degree']}, {entry['institution']}", st["body"])]
            for entry in cv["parsed_data"]["education"]
        ],
        colWidths=[date_width, width - date_width],
    )
    education.setStyle(
        TableStyle([*flush, ("FONT", (0, 0), (0, -1), options["font"], options["size"] - 1)])
    )

    story = [
        header,
        *_noise_block(cv, st),
        _p(headings["summary"], st["heading"]),
        _p(cv["summary"], st["body"]),
        _p(headings["experience"], st["heading"]),
        experience,
        _p(headings["skills"], st["heading"]),
        grid,
        _p(headings["education"], st["heading"]),
        education,
        *_extras_block(cv, options, st),
    ]
    doc.build(story)


def render_plain(cv: Record, options: Record, path: Path) -> None:
    """Typewriter style: no bold headings, bullets run together, contact details at the end."""
    st = _styles(options)
    body = st["body"]
    data = cv["parsed_data"]
    doc = SimpleDocTemplate(
        str(path),
        leftMargin=22 * mm,
        rightMargin=22 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
        **_doc_args(cv),
    )
    story: list[Flowable] = [
        _p(cv["full_name"].upper(), body),
        _p(cv["headline"], body),
        _p("-" * 48, body),
        _p(cv["summary"], body),
        *_noise_block(cv, st),
        Spacer(1, 8),
        _p("WHERE I HAVE WORKED", body),
    ]
    for job in data["work_history"]:
        dates = _date_range(job, options["date_style"])
        story.append(_p(f"{job['title']} at {job['company']} ({dates})", body))
        story.append(_p(". ".join(job["bullets"]) + ".", body))
        story.append(Spacer(1, 6))
    studied = "; ".join(
        f"{entry['degree']}, {entry['institution']}, {entry['grad_year']}"
        for entry in data["education"]
    )
    story += [
        _p("Tools and skills: " + " / ".join(data["skills"]), body),
        Spacer(1, 6),
        _p("Studied: " + studied, body),
        _p("Speaks: " + ", ".join(cv["languages"]), body),
    ]
    if cv["certifications"]:
        story.append(_p("Certificates: " + "; ".join(cv["certifications"]), body))
    story += [Spacer(1, 8), _p("Reach me: " + ", ".join(_contact(cv)), body)]
    doc.build(story)


RENDERERS: dict[str, Callable[[Record, Record, Path], None]] = {
    "classic": render_classic,
    "two_column": render_two_column,
    "table": render_table,
    "plain": render_plain,
}


# --------------------------------------------------------------------------- jobs and ratings


def _join(items: list[str]) -> str:
    """'a', 'a and b' or 'a, b and c'."""
    if len(items) < 2:
        return "".join(items)
    return f"{', '.join(items[:-1])} and {items[-1]}"


def _job_description(
    rng: random.Random,
    title: str,
    department: str,
    location: str,
    min_years: int,
    required: list[str],
    preferred: list[str],
    duties: list[str],
) -> str:
    if min_years == 0:
        experience = "No professional experience needed; internships and personal projects count"
    else:
        plural = "" if min_years == 1 else "s"
        experience = f"At least {min_years} year{plural} of relevant experience"

    style = rng.choice(("sections", "prose", "terse"))
    if style == "sections":
        lines = [
            "About the role",
            f"We are hiring a {title} for our {department} team ({location}).",
            "",
            "What you will do",
            *[f"- {duty}" for duty in duties],
            "",
            "What you bring",
            f"- {experience}",
            f"- Solid working knowledge of {_join(required)}",
            "",
            "Nice to have",
            f"- {_join(preferred)}",
        ]
        return "\n".join(lines)
    if style == "prose":
        tasks = _join([duty[0].lower() + duty[1:] for duty in duties])
        return (
            f"Our {department} team is growing and we are looking for a {title}. "
            f"You will {tasks}. {experience}. You should be confident with {_join(required)}. "
            f"Experience with {_join(preferred)} is a plus. Location: {location}."
        )
    return "\n".join(
        [
            f"{title} - {location}",
            f"Must have: {', '.join(required)}",
            f"Experience: {experience}",
            f"Good to have: {', '.join(preferred)}",
            f"Tasks: {'; '.join(duties)}",
        ]
    )


def build_job(index: int, seed: int) -> Record:
    """Return one job description, using the same field names as the jobs API."""
    rng = random.Random(f"{seed}:job:{index}")
    family = FAMILIES[index % len(FAMILIES)]
    seniority = JOB_SENIORITY_CYCLE[index % len(JOB_SENIORITY_CYCLE)]
    title = family.titles[SENIORITIES.index(seniority)]
    required = rng.sample(family.core, rng.randint(4, 6))
    remaining = [skill for skill in family.core + family.extra if skill not in required]
    preferred = rng.sample(remaining, rng.randint(2, 4))
    min_years = MIN_EXPERIENCE[seniority] + rng.randint(0, 1)
    location = rng.choice(JOB_LOCATIONS)
    employment_type = rng.choices(("full_time", "part_time", "contract"), weights=(8, 1, 2))[0]
    duties = rng.sample(family.duties, rng.randint(3, 4))
    return {
        "job_id": f"J{index + 1:02d}",
        "synthetic": True,
        "title": title,
        "department": family.department,
        "location": location,
        "employment_type": employment_type,
        "description": _job_description(
            rng, title, family.department, location, min_years, required, preferred, duties
        ),
        "required_skills": required,
        "preferred_skills": preferred,
        "min_experience_years": min_years,
        "role_family": family.key,
        "seniority": seniority,
    }


def build_rating_pairs(
    cvs: list[Record], jobs: list[Record], seed: int, per_job: int
) -> list[tuple[str, str]]:
    """Pick the (candidate_id, job_id) pairs people are asked to rate.

    About two thirds of each job's candidates come from the job's own family, so the
    ratings cover the whole 0-3 scale instead of being mostly zeros.
    """
    pairs: list[tuple[str, str]] = []
    for job in jobs:
        rng = random.Random(f"{seed}:pairs:{job['job_id']}")
        same = [cv["candidate_id"] for cv in cvs if cv["role_family"] == job["role_family"]]
        other = [cv["candidate_id"] for cv in cvs if cv["role_family"] != job["role_family"]]
        same_count = min(len(same), (per_job * 2 + 2) // 3)
        other_count = min(len(other), per_job - same_count)
        chosen = rng.sample(same, same_count) + rng.sample(other, other_count)
        pairs += [(candidate_id, job["job_id"]) for candidate_id in sorted(chosen)]
    return pairs


# --------------------------------------------------------------------------- output


def _write_json(path: Path, data: Any) -> None:
    text = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    path.write_text(text, encoding="utf-8", newline="\n")


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _clear(directory: Path, patterns: tuple[str, ...]) -> None:
    """Remove files from an earlier run. Only touches the file names this script writes."""
    for pattern in patterns:
        for old_file in directory.glob(pattern):
            old_file.unlink()


def _positive(value: str) -> int:
    number = int(value)
    if number < 1:
        raise argparse.ArgumentTypeError("must be 1 or more")
    return number


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--seed", type=int, default=42, help="random seed (default: 42)")
    parser.add_argument("--cvs", type=_positive, default=100, help="number of CVs (default: 100)")
    parser.add_argument(
        "--jobs", type=_positive, default=20, help="number of job descriptions (default: 20)"
    )
    parser.add_argument(
        "--pairs-per-job",
        type=_positive,
        default=15,
        help="candidates to rate for each job (default: 15)",
    )
    parser.add_argument(
        "--year",
        type=int,
        default=2026,
        help="year treated as 'now' for work history dates (default: 2026)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parent / "output",
        help="output directory (default: ./output next to this script)",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    cv_dir, job_dir = args.out / "cvs", args.out / "jobs"
    cv_dir.mkdir(parents=True, exist_ok=True)
    job_dir.mkdir(parents=True, exist_ok=True)
    _clear(cv_dir, ("C*.pdf", "C*.json"))
    _clear(job_dir, ("J*.json",))

    fakers = {locale: Faker(locale) for locale in LOCALES}
    cvs = []
    cv_entries = []
    for index in range(args.cvs):
        cv, options = build_cv(index, args.seed, args.year, fakers)
        pdf_path = cv_dir / cv["pdf_file"]
        RENDERERS[cv["layout"]](cv, options, pdf_path)
        _write_json(cv_dir / f"{cv['candidate_id']}.json", cv)
        cvs.append(cv)
        cv_entries.append(
            {
                "candidate_id": cv["candidate_id"],
                "role_family": cv["role_family"],
                "seniority": cv["seniority"],
                "layout": cv["layout"],
                "pdf": f"cvs/{cv['pdf_file']}",
                "json": f"cvs/{cv['candidate_id']}.json",
                "pdf_sha256": _sha256(pdf_path),
            }
        )

    jobs = [build_job(index, args.seed) for index in range(args.jobs)]
    for job in jobs:
        _write_json(job_dir / f"{job['job_id']}.json", job)

    pairs = build_rating_pairs(cvs, jobs, args.seed, args.pairs_per_job)
    with open(args.out / "ratings_template.csv", "w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerow(["candidate_id", "job_id", "rating"])
        writer.writerows([candidate_id, job_id, ""] for candidate_id, job_id in pairs)

    _write_json(
        args.out / "manifest.json",
        {
            "generator_version": GENERATOR_VERSION,
            "seed": args.seed,
            "reference_year": args.year,
            "packages": {
                "Faker": metadata.version("Faker"),
                "reportlab": metadata.version("reportlab"),
            },
            "counts": {"cvs": len(cvs), "jobs": len(jobs), "rating_pairs": len(pairs)},
            "cvs": cv_entries,
            "jobs": [
                {
                    "job_id": job["job_id"],
                    "role_family": job["role_family"],
                    "seniority": job["seniority"],
                    "json": f"jobs/{job['job_id']}.json",
                }
                for job in jobs
            ],
        },
    )

    print(
        f"Wrote {len(cvs)} CVs, {len(jobs)} jobs and {len(pairs)} rating pairs "
        f"to {args.out} (seed {args.seed})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
